#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'giraffe', path: '.'
cookbook 'graphite'

cookbook 'fixtures', path: 'test/unit/fixtures'
cookbook 'test', path: 'test/integration/cookbooks/test'
